In [2]:
import numpy as np
arr=np.arange(10)**2
print(arr)


[ 0  1  4  9 16 25 36 49 64 81]


In [3]:
arr[0]

0

In [4]:
arr[2:]

array([ 4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [5]:
arr[-4 ]

36

In [6]:
arr[-4:]

array([36, 49, 64, 81], dtype=int32)

In [7]:
arr[-1:-4:-1]

array([81, 64, 49], dtype=int32)

In [ ]:
arr[1:1] #no output

In [ ]:
arr[2:-2]

## 2D arrays

In [ ]:
students = np.array([['Rocky','shaggy','Edge','Mark'],[65,78,90,81],[71,82,79,92]])

In [ ]:
type(students)

In [ ]:
len(students)

In [ ]:
students.size

In [ ]:
students

In [ ]:
students[0] #1st raw

In [ ]:
students[2:4]

In [ ]:
students[2,3] #row,column

In [ ]:
students[0:1,2:3]

In [ ]:
students[0,1]

#hello 

##hello 

In [ ]:
#all rows and column1

In [ ]:
students[:,1:3]

In [ ]:
#all rows and column1 and column2 

In [ ]:
students[:,1:3]

In [ ]:
#all rows column 0 and 1

In [ ]:
students[0:2,:]

In [ ]:
#all rows and columns

In [ ]:
students[:]

In [ ]:
#the last raw

In [ ]:
students[-1,:]

In [ ]:
students[1,...] #1st row and all the values #lipses

In [4]:
randMat=np.random.rand(4,3)

In [6]:
randMat

array([[0.00733725, 0.2052592 , 0.17624415],
       [0.96197948, 0.78730687, 0.77594813],
       [0.53975081, 0.17170731, 0.14972005],
       [0.41277366, 0.21486146, 0.31837517]])

In [7]:
randMat[1,:]

array([0.96197948, 0.78730687, 0.77594813])

In [8]:
randMat[1,:] = 0

In [9]:
randMat

array([[0.00733725, 0.2052592 , 0.17624415],
       [0.        , 0.        , 0.        ],
       [0.53975081, 0.17170731, 0.14972005],
       [0.41277366, 0.21486146, 0.31837517]])

In [11]:
randMat[[0,2,3]] #slicingmultiple rows at random position

array([[0.00733725, 0.2052592 , 0.17624415],
       [0.53975081, 0.17170731, 0.14972005],
       [0.41277366, 0.21486146, 0.31837517]])

## 3-d array

In [24]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [5, 5, 8]]])

In [27]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr[1]

array([[3, 2, 1],
       [5, 5, 8]])

In [29]:
arr[0,0]

array([1, 2, 3])

In [30]:
arr[0,0:2,1]

array([2, 5])

In [34]:
 arr = np.arange(10)**2
for i in arr : 
     print(i)

0
1
4
9
16
25
36
49
64
81


In [ ]:
--