In [2]:
import numpy as np

## converting list to array - can have only one data type 

In [8]:
arr = np.array(object=[1,2,3],dtype='str') #1-d
arr1=np.array(object=[1,2,3],dtype='int') #1-D
arr2 = np.array([[1.5,2,3],[4,5,6],[7,8,9]],dtype='float') #2-D
arr3 = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(5,5,8)]],dtype ='int') #3-D

In [9]:
print("1-D --> \n{} \n 2-D --> \n {} , 3-D --> \n {}".format(arr1,arr2,arr3) )

1-D --> 
[1 2 3] 
 2-D --> 
 [[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]] , 3-D --> 
 [[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [5 5 8]]]


In [10]:
print(type(arr1),type(arr2),type(arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [11]:
print(arr1.shape,arr2.shape,arr3.shape)

(3,) (3, 3) (2, 2, 3)


In [12]:
print(arr1.size,arr2.size,arr3.size)

3 9 12


In [13]:
print(arr1.ndim,arr2.ndim,arr3.ndim)

1 2 3


In [14]:
print(arr1.dtype,arr2.dtype,arr3.dtype)

int32 float64 int32


In [16]:
print(arr1.dtype.name,arr2.dtype.name,arr3.dtype.name)

int32 float64 int32


In [17]:
arr2.itemsize

8

In [20]:
arr1 = arr1.astype('float') #typeconversion
print(arr1.dtype,arr2.dtype,arr3.dtype)

float64 float64 int32


In [21]:
print(arr1)

[1. 2. 3.]


In [22]:
print(arr2)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [23]:
print(np.delete(arr=arr2, obj = [0,2,4])) #obj is the index of the elments needs to be deleted

[2. 4. 6. 7. 8. 9.]


In [24]:
print(arr2)

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [25]:
np.delete(arr=arr2, obj =[1,2],axis=1) #if axis = 0 then it is abougt row, in the case of 1 it is column

array([[1.5],
       [4. ],
       [7. ]])

In [27]:
np.delete(arr=arr2,obj=[1,2],axis=0) 


array([[1.5, 2. , 3. ]])

In [28]:
l1 =[1,2,3]
l2 = [3,4,5]


In [29]:
l1+l2 #performs the concantination 

[1, 2, 3, 3, 4, 5]

In [32]:
l1=np.array([1,2,3])
l2=np.array([3,4,5])

In [34]:
l1+l2 #performs the addition

array([4, 6, 8])

In [35]:
a =np.array([10,10,10])
b = np.array([5,5,5])

In [36]:
a + b

array([15, 15, 15])

In [37]:
a/b

array([2., 2., 2.])

In [38]:
a % b

array([0, 0, 0], dtype=int32)

In [39]:
a *b 

array([50, 50, 50])

In [40]:
a < b 

array([False, False, False])

In [41]:
a >b 

array([ True,  True,  True])

In [42]:
a ** b

array([100000, 100000, 100000], dtype=int32)

## Dot function or Method 

In [44]:
a * b #element wise multiplication

array([50, 50, 50])

In [46]:
a  = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [47]:
print (' a : \n ',a)
print ('b : \n',b)

 a : 
  [[1 1]
 [0 1]]
b : 
 [[2 0]
 [3 4]]


In [48]:
a.dot(b) #gives element wise multiplication

array([[5, 4],
       [3, 4]])

In [49]:
np.dot(a,b)

array([[5, 4],
       [3, 4]])

In [58]:
a *= 3 #modifying an existing array
a

array([[243, 243],
       [  0, 243]])

In [60]:
b += b 
b

array([[ 8,  0],
       [12, 16]])

## unary Operations

In [62]:
ages =np.array([12,15,18,20])

In [63]:
ages.sum()

65

In [65]:
ages.max()

20

In [66]:
ages.min()

12

In [67]:
numbers = np.arange(12).reshape(3,4)

In [68]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
## row and column operations

In [70]:
#in a 2D array axis 0 represents columns. axis 1 represenmt rows

In [71]:
numbers.sum(axis=1)

array([ 6, 22, 38])

In [72]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [75]:
numbers =np.arange(12).reshape(3,2,2)

In [74]:
numbers

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [76]:
## trignomatric functions

In [79]:
angles =np.array([0,30,45,60,90])

In [80]:
# angles neds jto be converted to radianns by multiplying by pi/180. only then can we apply trignomatric functions to our array

In [81]:
angles_radians = angles * np.pi/180

In [82]:
angles_radians 

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [90]:
print("sine of angles in the array")
print(np.sin(angles_radians))

sine of angles in the array
[0.         0.5        0.70710678 0.8660254  1.        ]


In [91]:
print('cosines of angles in the array')
print(np.cos(angles_radians))

cosines of angles in the array
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [92]:
print('Tangent of angles in the array')
print(np.tan(angles_radians))

Tangent of angles in the array
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [93]:
#arcsin arcos arctan functions return the trignomatric inverse of sin,cos,and tan of the given angles. 

In [95]:
sin = np.sin(angles * np.pi / 100)
print("compute sine inverse of angles. returned values are in radians")
inv = np.arcsin(sin)
print(inv)

compute sine inverse of angles. returned values are in radians
[0.         0.9424778  1.41371669 1.25663706 0.31415927]


In [96]:
#np.degrees() converts radians to degrees

In [98]:
print("check results by converting to degrees")
print(np.degrees(inv))

check results by converting to degrees
[ 0. 54. 81. 72. 18.]


In [99]:
#statistical functions

In [100]:
test_scores = np.array([32,32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])

In [101]:
print("mean test scores of the students")
print(np.mean(test_scores))

mean test scores of the students
38.11222222222222


In [102]:
#madian 
print(np.median(test_scores))

43.34


In [104]:
mean =np.mean(test_scores)
median = np.median(test_scores)
sd = np.std(test_scores)
variance = np.var(test_scores)

In [105]:
print('Mean = %i' %mean)
print('Median =  %i' %median)
print('standard deviation = %i' %sd)
print('Variance = %i' %variance)

Mean = 38
Median =  43
standard deviation = 13
Variance = 188
