## numpy

In [73]:
import numpy as np 

In [74]:
numpArr = np.loadtxt(fname="winequality-red.csv",delimiter=",",skiprows=1)
numpArr

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [75]:
numpArr.ndim

2

In [76]:
numpArr[0:5,0:5]

array([[ 7.4  ,  0.7  ,  0.   ,  1.9  ,  0.076],
       [ 7.8  ,  0.88 ,  0.   ,  2.6  ,  0.098],
       [ 7.8  ,  0.76 ,  0.04 ,  2.3  ,  0.092],
       [11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075],
       [ 7.4  ,  0.7  ,  0.   ,  1.9  ,  0.076]])

In [77]:
numpArr = np.loadtxt(fname="winequality-red.csv",dtype="str",delimiter=",",skiprows=1) #datatype is changed to string
numpArr

array([['7.4', '0.7', '0.0', ..., '0.56', '9.4', '5'],
       ['7.8', '0.88', '0.0', ..., '0.68', '9.8', '5'],
       ['7.8', '0.76', '0.04', ..., '0.65', '9.8', '5'],
       ...,
       ['6.3', '0.51', '0.13', ..., '0.75', '11.0', '6'],
       ['5.9', '0.645', '0.12', ..., '0.71', '10.2', '5'],
       ['6.0', '0.31', '0.47', ..., '0.66', '11.0', '6']], dtype='<U20')

## Another way to load file using numpy.genfromtxt

In [78]:
numpArr = np.genfromtxt("winequality-red.csv",delimiter=",",names=True)
numpArr

array([(7.4, 0.7  , 0.  , 1.9, 0.076, 11., 34., 0.9978 , 3.51, 0.56,  9.4, 5.),
       (7.8, 0.88 , 0.  , 2.6, 0.098, 25., 67., 0.9968 , 3.2 , 0.68,  9.8, 5.),
       (7.8, 0.76 , 0.04, 2.3, 0.092, 15., 54., 0.997  , 3.26, 0.65,  9.8, 5.),
       ...,
       (6.3, 0.51 , 0.13, 2.3, 0.076, 29., 40., 0.99574, 3.42, 0.75, 11. , 6.),
       (5.9, 0.645, 0.12, 2. , 0.075, 32., 44., 0.99547, 3.57, 0.71, 10.2, 5.),
       (6. , 0.31 , 0.47, 3.6, 0.067, 18., 42., 0.99549, 3.39, 0.66, 11. , 6.)],
      dtype=[('fixed_acidity', '<f8'), ('volatile_acidity', '<f8'), ('citric_acid', '<f8'), ('residual_sugar', '<f8'), ('chlorides', '<f8'), ('free_sulfur_dioxide', '<f8'), ('total_sulfur_dioxide', '<f8'), ('density', '<f8'), ('pH', '<f8'), ('sulphates', '<f8'), ('alcohol', '<f8'), ('quality', '<f8')])

In [79]:
numpArr.shape

(1599,)

In [80]:
numpArr.dtype

dtype([('fixed_acidity', '<f8'), ('volatile_acidity', '<f8'), ('citric_acid', '<f8'), ('residual_sugar', '<f8'), ('chlorides', '<f8'), ('free_sulfur_dioxide', '<f8'), ('total_sulfur_dioxide', '<f8'), ('density', '<f8'), ('pH', '<f8'), ('sulphates', '<f8'), ('alcohol', '<f8'), ('quality', '<f8')])

In [81]:
numpArr.dtype.name

'void768'

In [82]:
numpArr.ndim

1

In [83]:
numpArr.size

1599

In [84]:
numpArr[0]

(7.4, 0.7, 0., 1.9, 0.076, 11., 34., 0.9978, 3.51, 0.56, 9.4, 5.)

In [85]:
numpArr[1]

(7.8, 0.88, 0., 2.6, 0.098, 25., 67., 0.9968, 3.2, 0.68, 9.8, 5.)

In [86]:
np.savetxt(fname="myarray.csv",X=numpArr[:30],delimiter=",")

In [87]:
wines = np.genfromtxt(fname="winequality-red.csv",dtype="float",delimiter=",",skip_header=1)

In [88]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [89]:
wines[0:2,1:3] #1st 2 rows and 2nd and 3rd column

array([[0.7 , 0.  ],
       [0.88, 0.  ]])

In [90]:
print(wines.dtype)

float64


In [91]:
wines.astype(int) #conversion into into
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [92]:
np.unique(wines[3:5])

array([ 0.    ,  0.075 ,  0.076 ,  0.28  ,  0.56  ,  0.58  ,  0.7   ,
        0.9978,  0.998 ,  1.9   ,  3.16  ,  3.51  ,  5.    ,  6.    ,
        7.4   ,  9.4   ,  9.8   , 11.    , 11.2   , 17.    , 34.    ,
       60.    ])

In [93]:
wines[:,11] #11th index. 12th number

array([5., 5., 5., ..., 6., 5., 6.])

In [94]:
np.unique(wines[:,11])

array([3., 4., 5., 6., 7., 8.])

In [95]:
wines[:,11] > 7

array([False, False, False, ..., False, False, False])

In [96]:
~(wines[:,11]>7) #negat

array([ True,  True,  True, ...,  True,  True,  True])

In [97]:
winesNew = wines[np.logical_and(wines[:,10]>10,wines[:,11] > 7)]
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [98]:
winesNew.astype(int)

array([[ 7,  0,  0,  3,  0, 15, 37,  0,  3,  0, 12,  8],
       [10,  0,  0,  6,  0,  5, 13,  0,  3,  0, 12,  8],
       [ 5,  0,  0,  1,  0, 12, 88,  0,  3,  0, 12,  8],
       [11,  0,  0,  5,  0,  6, 19,  0,  3,  0, 13,  8],
       [ 9,  0,  0,  2,  0,  6, 17,  0,  3,  0, 11,  8],
       [10,  0,  0,  2,  0,  5, 16,  0,  3,  0, 11,  8],
       [10,  0,  0,  2,  0,  5, 16,  0,  3,  0, 11,  8],
       [ 5,  0,  0,  2,  0, 19, 50,  0,  3,  0, 14,  8],
       [ 7,  0,  0,  2,  0, 34, 45,  0,  3,  0, 12,  8],
       [ 9,  0,  0,  1,  0,  7, 16,  0,  3,  0, 12,  8],
       [10,  0,  0,  1,  0, 42, 74,  0,  2,  0, 11,  8],
       [ 7,  0,  0,  2,  0,  8, 17,  0,  3,  0, 13,  8],
       [ 8,  0,  0,  1,  0,  6, 12,  0,  3,  0, 11,  8],
       [ 5,  0,  0,  1,  0, 28, 87,  0,  3,  0, 14,  8],
       [ 7,  0,  0,  2,  0, 15, 29,  0,  3,  0, 11,  8],
       [ 7,  0,  0,  1,  0, 17, 24,  0,  3,  0, 11,  8]])

In [100]:
 wines.transpose() #transpose shape

array([[ 7.4  ,  7.8  ,  7.8  , ...,  6.3  ,  5.9  ,  6.   ],
       [ 0.7  ,  0.88 ,  0.76 , ...,  0.51 ,  0.645,  0.31 ],
       [ 0.   ,  0.   ,  0.04 , ...,  0.13 ,  0.12 ,  0.47 ],
       ...,
       [ 0.56 ,  0.68 ,  0.65 , ...,  0.75 ,  0.71 ,  0.66 ],
       [ 9.4  ,  9.8  ,  9.8  , ..., 11.   , 10.2  , 11.   ],
       [ 5.   ,  5.   ,  5.   , ...,  6.   ,  5.   ,  6.   ]])

In [101]:
wines[1,:].reshape((2,6)) #elements 2*6 array

array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ]])

In [102]:
#combining numy arrays 
whitewines = np.genfromtxt(fname='winequality-white.csv',delimiter=",",skip_header=1)
print(whitewines.shape,wines.shape)

(4898,) (1599, 12)
