In [1]:
import numpy as np

In [6]:
#split

In [2]:
arr=np.arange(3)

In [5]:
np.S plit(arr,3)

AttributeError: module 'numpy' has no attribute 'Split'

In [7]:
arr = np.array([('a','b','c','d'),('e','f','g','h')])

In [17]:
a,b = np.hsplit(arr,2) #horizontal split

In [11]:
print(a)


[['a' 'b']
 ['e' 'f']]


In [12]:
print(b)

[['c' 'd']
 ['g' 'h']]


In [18]:
a,b = np.vsplit(arr,2) #vertical Split

In [19]:
print(a)

[['a' 'b' 'c' 'd']]


In [20]:
print(b)

[['e' 'f' 'g' 'h']]


## unpacking

In [25]:
a,b=arr

In [26]:
print(a)

['a' 'b' 'c' 'd']


In [27]:
print(b)

['e' 'f' 'g' 'h']


In [29]:
arr = np.array(['a','b','c','d'])

In [32]:
a1 = arr.view

In [31]:
a2 = arr.view

In [34]:
a1

<function ndarray.view>

In [35]:
l1 =[1,2,3]

In [36]:
l2 = l1

In [37]:
del l1[0]

In [38]:
print(l1)

[2, 3]


In [39]:
print(l2)

[2, 3]


In [40]:
l1 = [1,2,3]

In [45]:
l2 =l1.copy()

In [46]:
del l1[0]

In [47]:
print(l1)

[3]


In [52]:
print(l2)

[2, 3]


In [53]:
arr = np.array(['a','b','c','d'])
a1 = arr.view()
a2 = arr.view()
a1.base is arr

True

In [64]:
arr = np.array(['a','b','c','d'])
a1 = arr.copy()
a2 = arr.copy()
a1.base is arr

False

In [65]:
np.array([[2,3,4],[2,4,5]])

array([[2, 3, 4],
       [2, 4, 5]])

## broadcasting

In [68]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,6,6])

In [69]:
a1*a2

array([ 5, 12, 18, 24])

In [70]:
a1*20

array([20, 40, 60, 80])

In [71]:
a1 = np.array([1,2,3,4,5,6]).reshape(2,3)

In [74]:
a2 = np.array([2,3])

In [77]:
ya1*a2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 